# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('error_msg', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=1024)),
                ('cmd', models.CharField(max_length=255)),
                ('description', models.CharField(default=b'', max_length=255)),
                ('suffix', models.CharField(default=b'', max_length=255)),
                ('download_count', models.IntegerField(default=0)),
                ('hashid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpshare_converted_storage', to='hashid.HashID')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1024)),
                ('persist', models.BooleanField(default=False)),
                ('uploaded', models.BooleanField(default=False)),
                ('size', models.IntegerField(default=0)),
                ('mimetype', models.CharField(default=b'application/octet-stream', max_length=255)),
                ('extension', models.CharField(default=b'', max_length=255)),
                ('extrainfo', models.CharField(default=b'', max_length=255)),
                ('sha1sum', models.CharField(default=b'', max_length=40)),
                ('persistentId', models.CharField(db_index=True, default=b'', max_length=255)),
                ('download_count', models.IntegerField(default=0)),
                ('hashid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpshare_storage', to='hashid.HashID')),
            ],
        ),
        migrations.CreateModel(
            name='StorageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persist', models.BooleanField(default=False)),
                ('hashid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpshare_storage_group', to='hashid.HashID')),
                ('storages', models.ManyToManyField(related_name='groups', to='hpshare.Storage')),
            ],
        ),
        migrations.AddField(
            model_name='convertedstorage',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converted_storage', to='hpshare.Storage'),
        ),
    ]
