# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-19 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpshare', '0004_auto_20160205_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedstorage',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
