# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-19 12:51
from __future__ import unicode_literals

from django.db import migrations
import re


def populate_is_preview(apps, schema_editor):
    ConvertedStorage = apps.get_model('hpshare', 'ConvertedStorage')
    for storage in ConvertedStorage.objects.all():
        storage.is_preview = storage.description.startswith('Preview:')
        storage.description = re.sub(r'^Preview:', '', storage.description)
        storage.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hpshare', '0005_convertedstorage_is_preview'),
    ]

    operations = [
        migrations.RunPython(populate_is_preview),
    ]
