# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashid', '0002_hashid_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=4096)),
                ('permanent', models.BooleanField(default=False)),
                ('hashid', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hpshorten_redirect', to='hashid.HashID')),
            ],
        ),
        migrations.CreateModel(
            name='StaticRedirection',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('redirection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hpshorten.Redirection')),
            ],
        ),
    ]
